apiVersion: v1
kind: page
spec:
  id: f8oRkwp
  title: Dolar Hoy
  content:
    - component: Text
      name: text
      children: []
      props:
        value: ¿Cuánto está el dolar en Argentina?
        variant: h2
        mode: text
        sx: 12
      layout:
        horizontalAlign: center
        verticalAlign: center
    - component: Text
      name: text1
      children: []
      props:
        value: 🇦🇷 Dólar oficial
        variant: h4
    - component: PageRow
      name: pageRow1
      children:
        [
          {
              component: Metric,
              name: oficial_compra,
              layout: { columnSize: 0.9991258741258742 },
              props:
                {
                  fullWidth: true,
                  label: 🇦🇷 La compra del dólar oficial hoy está,
                  value:
                    {
                      $$jsExpression: "parseFloat(dolarasiQuery.data[0][1].casa.compra)\n"
                    },
                  numberFormat: { kind: currency, currency: ARS }
                },
              children: []
            },
          {
              component: Metric,
              name: oficial_venta,
              layout: { columnSize: 1.0008741258741258 },
              props:
                {
                  label: 🇦🇷 La venta del dólar oficial hoy está,
                  value:
                    {
                      $$jsExpression: "parseFloat(dolarasiQuery.data[0][1].casa.venta)\n"
                    },
                  fullWidth: true,
                  numberFormat: { kind: currency, currency: ars }
                },
              children: []
            }
        ]
      props:
        justifyContent: start
    - component: Metric
      name: oficial_var
      children: []
      props:
        value:
          $$jsExpression: >
            parseFloat(dolarasiQuery.data[0][1].casa.variacion.replace(/,/g,
            ".") * 0.01)
        fullWidth: true
        label: Esto supone una variación del
        caption: con respecto a ayer
        numberFormat:
          kind: preset
          preset: percent
    - component: Text
      name: text2
      children: []
      props:
        value: 💵 Dólar Blue
        variant: h4
    - component: PageRow
      name: pageRow
      children:
        [
          {
              component: Metric,
              name: metric1,
              props:
                {
                  fullWidth: true,
                  label: 💵 La compra del dólar blue hoy está,
                  value:
                    {
                      $$jsExpression: "parseFloat(dolarasiQuery.data[1][1].casa.compra)\n"
                    }
                },
              children: []
            },
          {
              component: Metric,
              name: metric2,
              props:
                {
                  fullWidth: true,
                  label: 💵 La venta del dólar blue hoy está,
                  value:
                    {
                      $$jsExpression: "parseFloat(dolarasiQuery.data[1][1].casa.venta)\n"
                    }
                },
              children: []
            }
        ]
      props:
        justifyContent: start
    - component: Metric
      name: blue_var
      children: []
      props:
        value:
          $$jsExpression: >
            parseFloat(dolarasiQuery.data[1][1].casa.variacion.replace(/,/g,
            ".") * 0.01)
        fullWidth: true
        label: Esto supone una variación del
        numberFormat:
          kind: preset
          preset: percent
    - component: Text
      name: text3
      props:
        value: Información obtenida de la API de [Dolar$i](https://www.dolarsi.com/)
        mode: markdown
      children: []
  queries:
    - name: dolarasiQuery
      query:
        kind: rest
        url: https://www.dolarsi.com/api/api.php?type=valoresprincipales
        headers: []
        method: GET
        transform: return Object.entries(data)
        transformEnabled: true
        searchParams: []
  display: shell
